<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://auto.163.com/depreciate",34,87);
$z[2]=Array("page","http://dealers.auto.163.com/110100/(*)/sales/201803/(*).html",87,170);
$z[3]=Array("titlerule","<title>[内容]_网易汽车</title>",170,233);
$z[4]=Array("authorrule","",233,268);
$z[5]=Array("sourcerule","",268,303);
$z[6]=Array("bodyrule","<div class=\"post_text\" id=\"endText\">[内容]</div>",303,382);
$z[7]=Array("fyrule","",382,409);

?>