<?php
$z[0]=Array("charset","gb2312",0,35);
$z[1]=Array("list","http://auto.163.com/special/newsmoving/",35,97);
$z[2]=Array("page","http://auto.163.com/(*)/(*)/(*)/(*).html",97,160);
$z[3]=Array("titlerule","<title>[内容]_网易汽车</title>",160,223);
$z[4]=Array("authorrule","",223,258);
$z[5]=Array("sourcerule","",258,293);
$z[6]=Array("bodyrule","<div class=\"post_text\" id=\"endText\">[内容]</div>",293,372);
$z[7]=Array("fyrule","",372,399);

?>