<?php
$z[0]=Array("field","",93,122);
$z[0][4]['name']="typename";
$z[1]=Array("field","",171,199);
$z[1][4]['name']="typeurl";
$z[2]=Array("arclist","\r\n            <li class=\"first_news\"><a href=\"[field:arcurl/]\" title=\"[field:title /]\">[field:title /]</a></li>\r\n            ",338,526);
$z[2][4]['titlelen']="48";
$z[2][4]['row']="6";
$z[2][4]['limit']="0,6";
$z[3]=Array("arclist","\r\n            <li class=\"first_news\"><a href=\"[field:arcurl/]\" title=\"[field:title /]\">[field:title /]</a></li>\r\n            ",573,761);
$z[3][4]['titlelen']="48";
$z[3][4]['row']="6";
$z[3][4]['limit']="6,6";
$z[4]=Array("arclist"," <a class=\"nl_m_p1\" href=\"[field:arcurl/]\" title='[field:title /]'> <img src=\"[field:litpic/]\" alt=\"[field:title /]\" width=\"275\" height=\"160\" /> <span>[field:title /]</span> </a> ",843,1084);
$z[4][4]['titlelen']="50";
$z[4][4]['row']="1";
$z[4][4]['flag']="c,p";
$z[5]=Array("arclist","\r\n            <div class=\"nl_r_p_item\"> <a href=\"[field:arcurl/]\" title=\"[field:title /]\"><img src=\"[field:litpic/]\" alt=\"[field:title /]\" width=\"125\" height=\"90\" original=\"[field:litpic/]\"></a> <span>[field:title /]</span> </div>\r\n            ",1121,1436);
$z[5][4]['titlelen']="50";
$z[5][4]['row']="2";
$z[5][4]['flag']="p";
$z[5][4]['noflag']="c";

?>