<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://auto.163.com/special/newsmoving/",34,96);
$z[2]=Array("page","http://auto.163.com/(*)/(*)/(*)/(*).html",96,159);
$z[3]=Array("titlerule","<title>[内容]_网易汽车</title>",159,222);
$z[4]=Array("authorrule","",222,257);
$z[5]=Array("sourcerule","",257,292);
$z[6]=Array("bodyrule","<div class=\"post_text\" id=\"endText\">[内容]</div>",292,371);
$z[7]=Array("fyrule","",371,398);

?>