<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://world.gmw.cn/node_4661.htm",34,90);
$z[2]=Array("page","http://world.gmw.cn/(*)/(*)/content_(*).htm",90,156);
$z[3]=Array("titlerule","<title>[ÄÚÈİ]</title>",156,210);
$z[4]=Array("authorrule","",210,245);
$z[5]=Array("sourcerule","",245,280);
$z[6]=Array("bodyrule","<div id=\"contentMain\">[ÄÚÈİ]</div>",280,345);
$z[7]=Array("fyrule","",345,372);

?>