<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://world.gmw.cn/node_4661_[1-5].htm",34,96);
$z[2]=Array("page","http://world.gmw.cn/2018-03/(*)/content_279(*).htm",96,169);
$z[3]=Array("titlerule","<title>\n[内容]_国际要闻_光明网</title>\n",169,241);
$z[4]=Array("authorrule","",241,276);
$z[5]=Array("sourcerule","",276,311);
$z[6]=Array("bodyrule","<div id=\"contentMain\">[内容]</div>",311,376);
$z[7]=Array("fyrule","",376,403);

?>