{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/180317/1-1P31G52411.jpg' text='1979年3月12日，一群年轻的中国武警官兵在者阴山英勇奋战，成功地捍卫了中国领土的神圣不可侵犯。战斗中，来自云南边防杨万站的武警战士许跃、孟庆云等人英勇牺牲。30多年后，烈士许跃的家人及其生前战友来到麻栗坡，祭拜勇士的在天之灵。' width='800' height='534'} /uploads/allimg/180317/1-1P31G52411.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180317/1-1P31G52425.jpg' text='烈士许跃牺牲后，其亲属每年都会来到麻栗坡拜祭为国捐躯的亲人。' width='978' height='547'} /uploads/allimg/180317/1-1P31G52425.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180317/1-1P31G52433.jpg' text='站在哥哥的墓前，妹妹许跃萍情不自禁。' width='337' height='598'} /uploads/allimg/180317/1-1P31G52433.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180317/1-1P31G52441.jpg' text=' “还有爸爸亲手为你写的诗歌，一切都送给你”——每次，妹妹都会对哥哥有着说不尽的话' width='800' height='534'} /uploads/allimg/180317/1-1P31G52441.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180317/1-1P31G52450.jpg' text='“哥哥，你生前没有吃好的，穿好的，今天我们带来最好的酒”' width='900' height='598'} /uploads/allimg/180317/1-1P31G52450.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180317/1-1P31G52459.jpg' text='每一滴酒都代表着一份哀思！' width='978' height='551'} /uploads/allimg/180317/1-1P31G52459.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180317/1-1P31G52508.jpg' text='许跃萍向大家展示父亲亲手制作的纪念画册。闻得许跃牺牲的消息，老人特意立下一条家训：躺着的是英雄，站着的是好汉！在这家家训的感召下，许家人才辈出，涌现出了“全国劳模”、“省劳模”、“先进工作者”等英雄好汉。' width='800' height='534'} /uploads/allimg/180317/1-1P31G52508.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180317/1-1P31G52514.jpg' text='对于与哥哥一同长眠在麻栗坡的其他烈士，许跃萍给予了同样的爱。' width='888' height='598'} /uploads/allimg/180317/1-1P31G52514.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180317/1-1P31G52526.jpg' text='侯基成烈士，贵州黔西县人。据有关人员介绍，牺牲近40年来，是麻栗坡烈士陵园900多位烈士中惟一没有亲人看望的烈士，烈士许跃的妹妹许跃萍知晓后，每次到陵园扫墓，她都携家人为侯基成烈士扫墓: 他不是孤儿，我们就是他的姐妹' width='334' height='598'} /uploads/allimg/180317/1-1P31G52526.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180317/1-1P31G52539.jpg' text='“孤儿”烈士并不孤单——' width='800' height='448'} /uploads/allimg/180317/1-1P31G52539.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180317/1-1P31G52551.jpg' text='祖国不会忘记你！' width='399' height='598'} /uploads/allimg/180317/1-1P31G52551.jpg {/dede:img}
