<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/130702/1-130F2155225.jpg ",93,232);
$z[1][4]['ddimg']="/uploads/allimg/130702/1-130F2155225.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="";
$z[1][4]['height']="";
$z[2]=Array("img"," /uploads/allimg/130702/1-130F2155226.jpg ",234,373);
$z[2][4]['ddimg']="/uploads/allimg/130702/1-130F2155226.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="";
$z[2][4]['height']="";

?>