<?php
$z[0]=Array("charset","gb2312",0,35);
$z[1]=Array("list","http://auto.163.com/buy",35,81);
$z[2]=Array("page","http://auto.163.com/(*)/(*)/(*)/(*).html",81,144);
$z[3]=Array("titlerule","<title>[内容]_网易汽车</title>",144,207);
$z[4]=Array("authorrule","",207,242);
$z[5]=Array("sourcerule","",242,277);
$z[6]=Array("bodyrule","<div class=\"post_text\" id=\"endText\">[内容]</div>",277,356);
$z[7]=Array("fyrule","",356,383);

?>