<?php
$z[0]=Array("charset","gb2312",0,35);
$z[1]=Array("list","http://world.gmw.cn/node_4661.htm",35,91);
$z[2]=Array("page","http://world.gmw.cn/2018-03/14/content_27980222.htm",91,165);
$z[3]=Array("titlerule","<title>[ÄÚÈİ]</title>",165,219);
$z[4]=Array("authorrule","",219,254);
$z[5]=Array("sourcerule","",254,289);
$z[6]=Array("bodyrule","<div id=\"contentMain\">[ÄÚÈİ]</div>",289,354);
$z[7]=Array("fyrule","",354,381);

?>