<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://auto.163.com/buy",34,80);
$z[2]=Array("page","http://auto.163.com/(*)/(*)/(*)/(*).html",80,143);
$z[3]=Array("titlerule","<title>[内容]_网易汽车</title>",143,206);
$z[4]=Array("authorrule","",206,241);
$z[5]=Array("sourcerule","",241,276);
$z[6]=Array("bodyrule","<div class=\"post_text\" id=\"endText\">[内容]</div>",276,355);
$z[7]=Array("fyrule","",355,382);

?>