<?php
$z[0]=Array("pagestyle"," @me= (@me==3 ? '\r\n    <li>' : '');",6,89);
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",99,115);
$z[2]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",134,219);
$z[2][4]['runphp']="yes";
$z[3]=Array("imgsrc","",231,246);
$z[4]=Array("imgwidth","",260,278);
$z[5]=Array("alttext","",284,301);
$z[6]=Array("linkurl","",446,462);
$z[7]=Array("pagestyle","@me = (@me==3 ? 'class=\"title\"' : '');",464,550);
$z[7][4]['runphp']="yes";
$z[8]=Array("pagestyle"," @me = (@me==3 ? '</li>' : ''); ",558,638);
$z[8][4]['runphp']="yes";

?>