<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://auto.163.com/depreciate",34,87);
$z[2]=Array("page","http://dealers.auto.163.com/110100/(*)/sales/(*)/(*).html",87,167);
$z[3]=Array("titlerule","<title>[内容]_网易汽车</title>",167,230);
$z[4]=Array("authorrule","",230,265);
$z[5]=Array("sourcerule","",265,300);
$z[6]=Array("bodyrule","<div class=\"post_text\" id=\"endText\">[内容]</div>",300,379);
$z[7]=Array("fyrule","",379,406);

?>