<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/140120/1-140120230023.jpg ",93,240);
$z[1][4]['ddimg']="/uploads/allimg/140120/1-140120230023.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="900";
$z[1][4]['height']="624";
$z[2]=Array("img"," /uploads/allimg/140120/1-140120230024.jpg ",242,389);
$z[2][4]['ddimg']="/uploads/allimg/140120/1-140120230024.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="915";
$z[2][4]['height']="609";

?>