<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://world.gmw.cn/node_4661.htm",34,90);
$z[2]=Array("page","http://world.gmw.cn/(*)/(*)/(*).htm",90,148);
$z[3]=Array("titlerule","<title>[ÄÚÈİ]</title>",148,202);
$z[4]=Array("authorrule","",202,237);
$z[5]=Array("sourcerule","",237,272);
$z[6]=Array("bodyrule","<!--enpcontent-->[ÄÚÈİ]<!--/enpcontent-->\n",272,345);
$z[7]=Array("fyrule","",345,372);

?>