<?php
$z[0]=Array("charset","gb2312",0,35);
$z[1]=Array("list","http://auto.163.com/depreciate",35,88);
$z[2]=Array("page","http://dealers.auto.163.com/(*)/(*)/sales/(*)/(*).html",88,165);
$z[3]=Array("titlerule","<title>[内容]_网易汽车</title>",165,228);
$z[4]=Array("authorrule","",228,263);
$z[5]=Array("sourcerule","",263,298);
$z[6]=Array("bodyrule","<div class=\"post_text\" id=\"endText\">[内容]</div>",298,377);
$z[7]=Array("fyrule","",377,404);

?>