<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://world.gmw.cn/node_4661.htm",34,90);
$z[2]=Array("page","http://world.gmw.cn/2018-03/14/content_27980222.htm",90,164);
$z[3]=Array("titlerule","<title>[ÄÚÈİ]</title>",164,218);
$z[4]=Array("authorrule","",218,253);
$z[5]=Array("sourcerule","",253,288);
$z[6]=Array("bodyrule","<div id=\"contentMain\">[ÄÚÈİ]</div>",288,353);
$z[7]=Array("fyrule","",353,380);

?>