<?php
$z[0]=Array("charset","gb2312",0,35);
$z[1]=Array("list","http://auto.163.com/depreciate",35,88);
$z[2]=Array("page","http://dealers.auto.163.com/(*)/(*)/sales/201803/(*).html",88,168);
$z[3]=Array("titlerule","<title>[内容]_网易汽车</title>",168,231);
$z[4]=Array("authorrule","",231,266);
$z[5]=Array("sourcerule","",266,301);
$z[6]=Array("bodyrule","<div class=\"post_text\" id=\"endText\">[内容]</div>",301,380);
$z[7]=Array("fyrule","",380,407);

?>