<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://world.gmw.cn/node_4661_[1-5].htm",34,96);
$z[2]=Array("page","http://world.gmw.cn/2018-03/(*)/content_279(*).htm",96,169);
$z[3]=Array("titlerule","<title>\n[内容]\n_国际要闻\n_光明网</title>\n",169,243);
$z[4]=Array("authorrule","",243,278);
$z[5]=Array("sourcerule","",278,313);
$z[6]=Array("bodyrule","<div id=\"contentMain\">[内容]</div>",313,378);
$z[7]=Array("fyrule","",378,405);

?>