<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://world.gmw.cn/node_4661.htm",34,90);
$z[2]=Array("page","http://world.gmw.cn/2018-03/14/content_27980222.htm",90,164);
$z[3]=Array("titlerule","<title>\n[内容]\n_国际要闻\n_光明网</title>",164,237);
$z[4]=Array("authorrule","",237,272);
$z[5]=Array("sourcerule","",272,307);
$z[6]=Array("bodyrule","<div id=\"contentMain\">[内容]</div>",307,372);
$z[7]=Array("fyrule","",372,399);

?>