
-----------------------------------------------
<m:top name='模块管理' c='6,' display='block'>
    <m:item name='模块管理' link='module_main.php' rank='sys_module' target='main' />
    <m:item name='上传新模块' link='module_upload.php' rank='sys_module' target='main' />
    <m:item name='模块生成向导' link='module_make.php' rank='sys_module' target='main' />
    </m:top>
<m:top item='7' name='辅助插件' display='block'>
  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />
  <m:item name='挑错管理' link='erraddsave.php' rank='plus_挑错管理' target='main' />
<m:item name='百度新闻' link='baidunews.php' rank='plus_百度新闻' target='main' />
<m:item name='文件管理器' link='file_manage_main.php' rank='plus_文件管理器' target='main' />
<m:item name='友情链接' link='friendlink_main.php' rank='plus_友情链接模块' target='main' />
<m:item name='投票模块' link='vote_main.php' rank='plus_投票模块' target='main' />
<m:item name='bShare分享插件' link='plus_bshare.php' rank='plus_bShare分享插件' target='main' />
<m:item name='广告管理' link='ad_main.php' rank='plus_广告管理' target='main' />

</m:top>

<m:top name='畅言评论' display='block'>
<m:item name='畅言模块' link='changyan_main.php' rank='sys_Feedback' target='main'/>
<m:item name='评论管理' link='changyan_main.php?dopost=manage' rank='sys_Feedback' target='main'/>
<m:item name='数据统计' link='changyan_main.php?dopost=stat' rank='sys_Feedback' target='main'/>
<m:item name='导入导出' link='changyan_main.php?dopost=import' rank='sys_Feedback' target='main'/>
<m:item name='畅言设置' link='changyan_main.php?dopost=setting' rank='sys_Feedback' target='main'/>
</m:top>
<m:top name='众大云采集' display='block' rank=''>
  <m:item name='单篇采集' link='hzw_article_add.php' rank='' target='main' />
  <m:item name='批量采集' link='hzw_batch.php' rank='' target='main' />
  <m:item name='实时采集' link='hzw_trueTime.php' rank='' target='main' />
  <m:item name='网址采集' link='hzw_url.php' rank='' target='main' />
  <m:item name='定时采集' link='hzw_fixedTime.php' rank='' target='main' />
  <m:item name='待发布' link='hzw_pending.php' rank='' target='main' />
  <m:item name='已发布' link='hzw_released.php' rank='' target='main' />
  <m:item name='伪原创' link='hzw_original.php' rank='' target='main' />
  <m:item name='关键词' link='hzw_keyword.php' rank='' target='main' />
  <m:item name='回收站' link='hzw_recycle.php' rank='' target='main' />
  <m:item name='帮助说明' link='hzw_help.php' rank='' target='main' />  
</m:top>
<m:top name='采集侠' c='1,' display='block' rank=''>
<m:item name='基本设置' link='cjx.php?ac=setting' rank='' target='main' />
<m:item name='高级设置' link='cjx.php?ac=advanced' rank='' target='main' />
<m:item name='伪原创设置' link='cjx.php?ac=seo' rank='' target='main' />
<m:item name='搜索优化设置' link='cjx.php?ac=search' rank='' target='main' />
<m:item name='采集任务' link='cjx.php?ac=task' rank='' target='main' />
<m:item name='超级采集' link='cjx.php?ac=advcjx' rank='' target='main' />
<m:item name='在线更新' link='cjx.php?ac=update' rank='' target='main' />
<m:item name='我的授权' link='cjx.php?ac=credits' rank='' target='main' />
<m:item name='帮助中心' link='http://www.dedeapps.com/Related/?plugin=caijixia' rank='' target='main' />
</m:top>








-----------------------------------------------
