<?php
$z[0]=Array("field","",215,241);
$z[0][4]['name']="title";
$z[1]=Array("global","",242,268);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",309,331);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",371,422);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1035,1074);
$z[4][4]['filename']="n_head_m.htm";
$z[5]=Array("field","",1126,1152);
$z[5][4]['name']="title";
$z[6]=Array("field","",1220,1274);
$z[6][4]['name']="pubdate";
$z[6][4]['function']="GetDateMk(@me)";
$z[7]=Array("field","",1312,1339);
$z[7][4]['name']="phpurl";
$z[8]=Array("field","",1363,1386);
$z[8][4]['name']="id";
$z[9]=Array("field","",1391,1415);
$z[9][4]['name']="mid";
$z[10]=Array("field","",1491,1519);
$z[10][4]['name']="writer";
$z[11]=Array("field","",1553,1578);
$z[11][4]['name']="body";
$z[12]=Array("include","",1644,1682);
$z[12][4]['filename']="share_m.htm";
$z[13]=Array("likearticle","\r\n        <li><a href=\"view.php?aid=[field:id/]\" title=\"[field:title /]\">[field:title /]</a></li>\r\n        ",1877,2043);
$z[13][4]['row']="5";
$z[13][4]['titlelen']="80";
$z[14]=Array("type","<a class=\"readMore\" href=\"list.php?tid=[field:id /]\">·µ»ØÀ¸Ä¿&gt;&gt;</a>",2088,2184);
$z[15]=Array("include","",2432,2469);
$z[15][4]['filename']="foot_m.htm";

?>