<?php
$z[0]=Array("field","",210,236);
$z[0][4]['name']="title";
$z[1]=Array("global","",237,263);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",303,325);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",364,415);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",930,969);
$z[4][4]['filename']="n_head_m.htm";
$z[5]=Array("field","",1017,1043);
$z[5][4]['name']="title";
$z[6]=Array("field","",1109,1163);
$z[6][4]['name']="pubdate";
$z[6][4]['function']="GetDateMk(@me)";
$z[7]=Array("field","",1201,1228);
$z[7][4]['name']="phpurl";
$z[8]=Array("field","",1252,1275);
$z[8][4]['name']="id";
$z[9]=Array("field","",1280,1304);
$z[9][4]['name']="mid";
$z[10]=Array("field","",1380,1408);
$z[10][4]['name']="writer";
$z[11]=Array("field","",1447,1472);
$z[11][4]['name']="body";
$z[12]=Array("pagebreak","",1510,1527);
$z[13]=Array("include","",1593,1631);
$z[13][4]['filename']="share_m.htm";
$z[14]=Array("likearticle","\n        <li><a href=\"view.php?aid=[field:id/]\" title=\"[field:title /]\">[field:title /]</a></li>\n        ",1808,1972);
$z[14][4]['row']="5";
$z[14][4]['titlelen']="80";
$z[15]=Array("type","<a class=\"readMore\" href=\"list.php?tid=[field:id/]\">·µ»ØÀ¸Ä¿&gt;&gt;</a>",2012,2107);
$z[16]=Array("include","",2447,2484);
$z[16][4]['filename']="foot_m.htm";

?>