<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150729/1-150H9104639.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/150729/1-150H9104639.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="550";
$z[1][4]['height']="386";
$z[2]=Array("img"," /uploads/allimg/150729/1-150H9104639-50.jpg ",240,391);
$z[2][4]['ddimg']="/uploads/allimg/150729/1-150H9104639-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="400";
$z[2][4]['height']="222";

?>