<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://world.gmw.cn/node_4661.htm",34,90);
$z[2]=Array("page","http://world.gmw.cn/2018-03/14/content_(*).htm",90,159);
$z[3]=Array("titlerule","<title>\n[内容]\n_国际要闻\n_光明网</title>",159,232);
$z[4]=Array("authorrule","",232,267);
$z[5]=Array("sourcerule","",267,302);
$z[6]=Array("bodyrule","<div id=\"contentMain\">[内容]</div>",302,367);
$z[7]=Array("fyrule","",367,394);

?>