<?php
$z[0]=Array("charset","gb2312",0,35);
$z[1]=Array("list","http://ty.house.163.com/news/",35,87);
$z[2]=Array("page","http://ty.house.163.com/(*)/(*)/(*)/(*).html",87,154);
$z[3]=Array("titlerule","<title>[内容]_网易房产</title>",154,217);
$z[4]=Array("authorrule","",217,252);
$z[5]=Array("sourcerule","",252,287);
$z[6]=Array("bodyrule","<div class=\"post_text\" id=\"endText\">[内容]</div>",287,366);
$z[7]=Array("fyrule","",366,393);

?>