<?php
$z[0]=Array("charset","gb2312",0,35);
$z[1]=Array("list","http://auto.163.com/depreciate",35,88);
$z[2]=Array("page","http://auto.163.com/(*)/(*)/(*)/(*).html",88,151);
$z[3]=Array("titlerule","<title>[内容]_网易汽车</title>",151,214);
$z[4]=Array("authorrule","",214,249);
$z[5]=Array("sourcerule","",249,284);
$z[6]=Array("bodyrule","<div class=\"post_text\" id=\"endText\">[内容]</div>",284,363);
$z[7]=Array("fyrule","",363,390);

?>