<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://house.ifeng.com/",34,80);
$z[2]=Array("page","http://house.ifeng.com/detail/(*)/(*)_0.shtml",80,148);
$z[3]=Array("titlerule","<title>[内容]！ ——凤凰网房产北京</title>",148,223);
$z[4]=Array("authorrule","",223,258);
$z[5]=Array("sourcerule","",258,293);
$z[6]=Array("bodyrule","<div class=\"article\">[内容]</div>",293,357);
$z[7]=Array("fyrule","",357,384);

?>