<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150729/1-150H9104R9.jpg ",93,236);
$z[1][4]['ddimg']="/uploads/allimg/150729/1-150H9104R9.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="480";
$z[1][4]['height']="349";
$z[2]=Array("img"," /uploads/allimg/150729/1-150H9104R9-50.jpg ",238,387);
$z[2][4]['ddimg']="/uploads/allimg/150729/1-150H9104R9-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="400";
$z[2][4]['height']="222";

?>