<DIV class="cell">
 <a href="[field:arcurl/]" title="[field:title /]" target="_blank"><img width="230px" src="[field:litpic/]" alt="[field:title /]"/></a>
 <P><a href="[field:arcurl/]" title="[field:title /]" target="_blank">[field:title /]</a><br><font style="color:#888888">[field:description function="cn_substr(@me,100)"/]...</font><a href="[field:arcurl/]" title="[field:title /]" target="_blank"><font style="color:#B1B1B1">[ฯ๊ว้]</font></a></P>
 </DIV>