
  <m:item name='单篇采集' link='hzw_article_add.php' rank='' target='main' />
  <m:item name='批量采集' link='hzw_batch.php' rank='' target='main' />
  <m:item name='实时采集' link='hzw_trueTime.php' rank='' target='main' />
  <m:item name='网址采集' link='hzw_url.php' rank='' target='main' />
  <m:item name='定时采集' link='hzw_fixedTime.php' rank='' target='main' />
  <m:item name='待发布' link='hzw_pending.php' rank='' target='main' />
  <m:item name='已发布' link='hzw_released.php' rank='' target='main' />
  <m:item name='伪原创' link='hzw_original.php' rank='' target='main' />
  <m:item name='关键词' link='hzw_keyword.php' rank='' target='main' />
  <m:item name='回收站' link='hzw_recycle.php' rank='' target='main' />
  <m:item name='帮助说明' link='hzw_help.php' rank='' target='main' />  
