<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/130701/1-130F1153541.png ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/130701/1-130F1153541.png";
$z[1][4]['text']="";
$z[1][4]['width']="293";
$z[1][4]['height']="367";
$z[2]=Array("img"," /uploads/allimg/130701/1-130F1153542.jpg ",240,386);
$z[2][4]['ddimg']="/uploads/allimg/130701/1-130F1153542.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="800";
$z[2][4]['height']="1200";
$z[3]=Array("img"," /uploads/allimg/130701/1-130F1153542-50.jpg ",388,539);
$z[3][4]['ddimg']="/uploads/allimg/130701/1-130F1153542-50.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="524";
$z[3][4]['height']="800";

?>