<?php
$z[0]=Array("charset","gb2312",0,35);
$z[1]=Array("list","http://house.ifeng.com/",35,81);
$z[2]=Array("page","http://house.ifeng.com/detail/(*)/(*)_0.shtml",81,149);
$z[3]=Array("titlerule","<title>[内容]！ ——凤凰网房产北京</title>",149,224);
$z[4]=Array("authorrule","",224,259);
$z[5]=Array("sourcerule","",259,294);
$z[6]=Array("bodyrule","<div class=\"article\">[内容]</div>",294,358);
$z[7]=Array("fyrule","",358,385);

?>