<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150729/1-150H9104603.jpg ",93,242);
$z[1][4]['ddimg']="/uploads/allimg/150729/1-150H9104603.jpg";
$z[1][4]['text']="ÌÆæÌ";
$z[1][4]['width']="480";
$z[1][4]['height']="349";
$z[2]=Array("img"," /uploads/allimg/150729/1-150H9104604.jpg ",244,393);
$z[2][4]['ddimg']="/uploads/allimg/150729/1-150H9104604.jpg";
$z[2][4]['text']="ÌÆæÌ";
$z[2][4]['width']="400";
$z[2][4]['height']="600";

?>