{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/130701/1-130F1153T2.jpg' text='' width='700' height='876'} /uploads/allimg/130701/1-130F1153T2.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/130701/1-130F1153T2-50.jpg' text='' width='700' height='876'} /uploads/allimg/130701/1-130F1153T2-50.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/130701/1-130F1153T3.jpg' text='' width='700' height='876'} /uploads/allimg/130701/1-130F1153T3.jpg {/dede:img}
