{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/180317/1-1P31G45I4.jpg' text='据央视网最新消息，国产航母脚手架已全部拆除，海试在即。' width='600' height='412'} /uploads/allimg/180317/1-1P31G45I4.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180317/1-1P31G45K3.jpg' text='首艘国产航母的最新照片显示，舰岛相控阵雷达安装完毕，脚手架已全部拆除。这表明航母的主要设备均已安装完毕，进行相应调试后即将进行海试。' width='600' height='383'} /uploads/allimg/180317/1-1P31G45K3.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180317/1-1P31G45P3.jpg' text='国产航母舰艏滑跃甲板处还有不少设备' width='600' height='383'} /uploads/allimg/180317/1-1P31G45P3.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180317/1-1P31G45Q7.jpg' text='' width='406' height='598'} /uploads/allimg/180317/1-1P31G45Q7.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180317/1-1P31G45S1.jpg' text='' width='690' height='391'} /uploads/allimg/180317/1-1P31G45S1.jpg {/dede:img}
