<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/180317/1-1P31G45I4.jpg ",93,288);
$z[1][4]['ddimg']="/uploads/allimg/180317/1-1P31G45I4.jpg";
$z[1][4]['text']="据央视网最新消息，国产航母脚手架已全部拆除，海试在即。";
$z[1][4]['width']="600";
$z[1][4]['height']="412";
$z[2]=Array("img"," /uploads/allimg/180317/1-1P31G45K3.jpg ",290,563);
$z[2][4]['ddimg']="/uploads/allimg/180317/1-1P31G45K3.jpg";
$z[2][4]['text']="首艘国产航母的最新照片显示，舰岛相控阵雷达安装完毕，脚手架已全部拆除。这表明航母的主要设备均已安装完毕，进行相应调试后即将进行海试。";
$z[2][4]['width']="600";
$z[2][4]['height']="383";
$z[3]=Array("img"," /uploads/allimg/180317/1-1P31G45P3.jpg ",565,740);
$z[3][4]['ddimg']="/uploads/allimg/180317/1-1P31G45P3.jpg";
$z[3][4]['text']="国产航母舰艏滑跃甲板处还有不少设备";
$z[3][4]['width']="600";
$z[3][4]['height']="383";
$z[4]=Array("img"," /uploads/allimg/180317/1-1P31G45Q7.jpg ",742,883);
$z[4][4]['ddimg']="/uploads/allimg/180317/1-1P31G45Q7.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="406";
$z[4][4]['height']="598";
$z[5]=Array("img"," /uploads/allimg/180317/1-1P31G45S1.jpg ",885,1026);
$z[5][4]['ddimg']="/uploads/allimg/180317/1-1P31G45S1.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="690";
$z[5][4]['height']="391";

?>