{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/130701/1-130F1152914.jpg' text='青春美女狂野写真' width='220' height='315'} /uploads/allimg/130701/1-130F1152914.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/130701/1-130F1152915.jpg' text='青春美女狂野写真' width='220' height='329'} /uploads/allimg/130701/1-130F1152915.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/130701/1-130F1152915-50.jpg' text='青春美女狂野写真' width='220' height='340'} /uploads/allimg/130701/1-130F1152915-50.jpg {/dede:img}
