<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/160504/1-160504202J6.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/160504/1-160504202J6.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="797";
$z[1][4]['height']="598";
$z[2]=Array("img"," /uploads/allimg/160504/1-160504202K1.jpg ",240,385);
$z[2][4]['ddimg']="/uploads/allimg/160504/1-160504202K1.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="797";
$z[2][4]['height']="598";
$z[3]=Array("img"," /uploads/allimg/160504/1-160504202K6.jpg ",387,532);
$z[3][4]['ddimg']="/uploads/allimg/160504/1-160504202K6.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="797";
$z[3][4]['height']="598";
$z[4]=Array("img"," /uploads/allimg/160504/1-160504202Q7.jpg ",534,679);
$z[4][4]['ddimg']="/uploads/allimg/160504/1-160504202Q7.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="797";
$z[4][4]['height']="598";

?>