<?php
$z[0]=Array("channel","\n    | <a href=\"[field:typelink/]\" title=\"[field:typename function='substr(@me,0,16)'/]\" >[field:typename function='substr(@me,0,16)'/]</a> ",106,295);
$z[0][4]['row']="9";
$z[0][4]['type']="top";
$z[1]=Array("global","",422,455);
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",456,487);
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",642,664);
$z[3][4]['name']="cfg_wap";

?>