<?php
$z[0]=Array("channel","\n        <li><a href=\"list.php?tid=[field:id/]\">[field:typename/]</a></li>\n       ",440,572);
$z[0][4]['row']="15";
$z[0][4]['type']="top";
$z[1]=Array("type","<a href=\"list.php?tid=[field:id/]\" >[field:typename /]</a>",671,765);
$z[1][4]['typeid']="50";
$z[2]=Array("type","<a href=\"list.php?tid=[field:id/]\" >[field:typename /]</a>",768,863);
$z[2][4]['typeid']="108";
$z[3]=Array("type","<a href=\"list.php?tid=[field:id/]\" >[field:typename /]</a>",866,960);
$z[3][4]['typeid']="76";
$z[4]=Array("type","<a href=\"list.php?tid=[field:id/]\" >[field:typename /]</a>",963,1057);
$z[4][4]['typeid']="55";
$z[5]=Array("type","<a href=\"list.php?tid=[field:id/]\" >[field:typename /]</a>",1060,1154);
$z[5][4]['typeid']="81";
$z[6]=Array("type","<a href=\"list.php?tid=[field:id/]\" >[field:typename /]</a>",1157,1250);
$z[6][4]['typeid']="5";
$z[7]=Array("type","<a href=\"list.php?tid=[field:id/]\" >[field:typename /]</a>",1253,1348);
$z[7][4]['typeid']="132";

?>