<?php
$z[0]=Array("channel","\n        <li><a href=\"list.php?tid=[field:id/]\">[field:typename/]</a></li>\n       ",439,571);
$z[0][4]['row']="15";
$z[0][4]['type']="top";
$z[1]=Array("type","<a href=\"list.php?tid=[field:id/]\" >[field:typename /]</a>",670,764);
$z[1][4]['typeid']="50";
$z[2]=Array("type","<a href=\"list.php?tid=[field:id/]\" >[field:typename /]</a>",767,862);
$z[2][4]['typeid']="108";
$z[3]=Array("type","<a href=\"list.php?tid=[field:id/]\" >[field:typename /]</a>",865,959);
$z[3][4]['typeid']="76";
$z[4]=Array("type","<a href=\"list.php?tid=[field:id/]\" >[field:typename /]</a>",962,1056);
$z[4][4]['typeid']="55";
$z[5]=Array("type","<a href=\"list.php?tid=[field:id/]\" >[field:typename /]</a>",1059,1153);
$z[5][4]['typeid']="81";
$z[6]=Array("type","<a href=\"list.php?tid=[field:id/]\" >[field:typename /]</a>",1156,1249);
$z[6][4]['typeid']="5";
$z[7]=Array("type","<a href=\"list.php?tid=[field:id/]\" >[field:typename /]</a>",1252,1347);
$z[7][4]['typeid']="132";

?>