<?php
$z[0]=Array("field","",215,241);
$z[0][4]['name']="title";
$z[1]=Array("global","",242,268);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",309,331);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",371,422);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",957,996);
$z[4][4]['filename']="n_head_m.htm";
$z[5]=Array("field","",1045,1071);
$z[5][4]['name']="title";
$z[6]=Array("field","",1139,1193);
$z[6][4]['name']="pubdate";
$z[6][4]['function']="GetDateMk(@me)";
$z[7]=Array("field","",1231,1258);
$z[7][4]['name']="phpurl";
$z[8]=Array("field","",1282,1305);
$z[8][4]['name']="id";
$z[9]=Array("field","",1310,1334);
$z[9][4]['name']="mid";
$z[10]=Array("field","",1410,1438);
$z[10][4]['name']="writer";
$z[11]=Array("field","",1478,1503);
$z[11][4]['name']="body";
$z[12]=Array("include","",1577,1615);
$z[12][4]['filename']="share_m.htm";
$z[13]=Array("likearticle","\r\n        <li><a href=\"view.php?aid=[field:id/]\" title=\"[field:title /]\">[field:title /]</a></li>\r\n        ",1800,1966);
$z[13][4]['row']="5";
$z[13][4]['titlelen']="80";
$z[14]=Array("type","<a class=\"readMore\" href=\"list.php?tid=[field:id/]\">·µ»ØÀ¸Ä¿&gt;&gt;</a>",2011,2106);
$z[15]=Array("include","",2354,2391);
$z[15][4]['filename']="foot_m.htm";

?>