<?php
$z[0]=Array("field","",215,237);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",238,264);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",305,327);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",367,418);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",516,553);
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("field","",649,678);
$z[5][4]['name']="position";
$z[6]=Array("list","\r\n        <li><a href=\"view.php?aid=[field:id/]\" title=\"[field:title /]\">[field:title /]</a></li>\r\n        ",736,880);
$z[6][4]['pagesize']="20";
$z[7]=Array("pagelist","",941,1000);
$z[7][4]['listitem']="index,end,pre,next";
$z[7][4]['listsize']="3";
$z[8]=Array("include","",1015,1052);
$z[8][4]['filename']="foot_m.htm";

?>