<?php
$z[0]=Array("field","",609,631);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",632,658);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",699,721);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",761,812);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",908,945);
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("field","",1039,1068);
$z[5][4]['name']="position";
$z[6]=Array("list","\r\n      <div class='news_item'><img src=\"[field:litpic/]\" alt=\"[field:title /]\" class='avator75'>\r\n        <div class='news_detail cursor'><a href='view.php?aid=[field:id/]'><span>[field:title /]</span></a>\r\n          <p>[field:description function=\"cn_substr(@me,90)\"/]...</p>\r\n        </div>\r\n      </div>\r\n      ",1119,1470);
$z[6][4]['pagesize']="8";
$z[7]=Array("pagelist","",1526,1585);
$z[7][4]['listitem']="index,end,pre,next";
$z[7][4]['listsize']="3";
$z[8]=Array("include","",1604,1641);
$z[8][4]['filename']="foot_m.htm";

?>