<?php
$z[0]=Array("field","",215,237);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",238,264);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",305,327);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",367,418);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",953,990);
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("field","",1076,1105);
$z[5][4]['name']="position";
$z[6]=Array("list"," \r\n     <a target=\"_blank\" href=\"view.php?aid=[field:id/]\" title=\"[field:title /]\"><img src=\"[field:litpic/]\" alt=\"[field:title /]\" /><p>[field:title /]</p></a>\r\n    ",1151,1353);
$z[6][4]['pagesize']="8";
$z[7]=Array("pagelist","",1401,1460);
$z[7][4]['listitem']="index,end,pre,next";
$z[7][4]['listsize']="3";
$z[8]=Array("global","",1527,1560);
$z[8][4]['name']="cfg_powerby";
$z[9]=Array("global","",1578,1602);
$z[9][4]['name']="cfg_phone";
$z[10]=Array("global","",1609,1633);
$z[10][4]['name']="cfg_phone";

?>