<?php
$z[0]=Array("field","(@me==\"\")? @me=\" class='ntipcon'\":@me=\"\";",58,149);
$z[0][4]['name']="typeid";
$z[0][4]['runphp']="yes";
$z[1]=Array("channel","\r\n   <a href=\"[field:typelink/]\" title=\"[field:typename function='substr(@me,0,12)'/]\" >[field:typename function='substr(@me,0,12)'/]</a>\r\n   ",163,423);
$z[1][4]['row']="9";
$z[1][4]['type']="top";
$z[1][4]['currentstyle']="<a href='~typelink~' class='ntipcon'>~typename~</a>";
$z[2]=Array("global","",577,603);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",652,681);
$z[3][4]['name']="typename";
$z[4]=Array("global","",739,767);
$z[4][4]['name']="cfg_sinaweibo";
$z[5]=Array("type","[field:typelink /]",829,881);
$z[5][4]['typeid']="5";
$z[6]=Array("global","",1004,1026);
$z[6][4]['name']="cfg_wap";
$z[7]=Array("channel","\r\n     <a href=\"[field:typelink/]\" title=\"[field:typename function='substr(@me,0,16)'/]\" >[field:typename function='substr(@me,0,16)'/]</a>\r\n     ",1187,1450);
$z[7][4]['row']="9";
$z[7][4]['type']="sun";
$z[7][4]['currentstyle']="<a href='~typelink~' class='bghover'>~typename~</a>";

?>