<?php
$z[0]=Array("type","<a href=\"list.php?tid=[field:id/]\"><img src=\"/m/style/images/arrow_l.png\" alt=\"·µ»ØÀ¸Ä¿\" height=\"38\"></a>",48,176);
$z[1]=Array("type","<a href=\"list.php?tid=[field:id/]\">[field:typename /]</a>",237,317);
$z[2]=Array("channel","\n        <li><a href=\"list.php?tid=[field:id/]\">[field:typename/]</a></li>\n       ",627,759);
$z[2][4]['row']="15";
$z[2][4]['type']="top";

?>