<?php
$z[0]=Array("field","",255,277);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",278,304);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",329,358);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",391,449);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",929,957);
$z[4][4]['name']="cfg_mobileurl";
$z[5]=Array("field","",971,987);
$z[5][4]['name']="id";
$z[6]=Array("global","",1456,1484);
$z[6][4]['name']="cfg_mobileurl";
$z[7]=Array("field","",1498,1514);
$z[7][4]['name']="id";
$z[8]=Array("include","",7896,7931);
$z[8][4]['filename']="head.htm";
$z[9]=Array("channel","\r\n   <a href=\"[field:typelink/]\"><span>[field:typename/]</span></a>\r\n   ",7999,8119);
$z[9][4]['row']="9";
$z[9][4]['type']="sun";
$z[10]=Array("list","\r\n <DIV class=\"cell\">\r\n <a href=\"[field:arcurl/]\" title=\"[field:title /]\" target=\"_blank\"><img width=\"230px\" src=\"[field:litpic/]\" alt=\"[field:title /]\"/></a>\r\n <P><a href=\"[field:arcurl/]\" title=\"[field:title /]\" target=\"_blank\">[field:title /]</a><br><font style=\"color:#888888\">[field:description function=\"cn_substr(@me,100)\"/]...</font><a href=\"[field:arcurl/]\" title=\"[field:title /]\" target=\"_blank\"><font style=\"color:#B1B1B1\">[ฯ๊ว้]</font></a></P>\r\n </DIV>\r\n ",8131,8636);
$z[10][4]['pagesize']="50";
$z[11]=Array("pagelist","",8721,8792);
$z[11][4]['listitem']="info,index,end,pre,next,pageno";
$z[11][4]['listsize']="2";
$z[12]=Array("include","",9327,9362);
$z[12][4]['filename']="foot.htm";

?>